### ISSUE TITLE
Anhänge im Chat

### ISSUE THREAD

**Issue by bedivere** [4FriendsForum/Ffc#188]
Anhänge im Chat erlauben, die dann als Link (und nur als Link) im Chatlog auf einer eigenen Zeile zur Verfügung gestellt werden.

**Comment by bedivere** [comment]
Guggst du: https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects#Sending_files_using_a_FormData_object

**Comment by reneeb** [comment]
Und hier: http://stackoverflow.com/questions/5392344/sending-multipart-formdata-with-jquery-ajax#5976031

Kann ich auch gut gebraucht. Danke für den Hinweis ;-)

**Comment by bedivere** [comment]
Chat-Anhänge erhalten die Postid "0", ist vom DB-Design leider nicht ganz vorrausschauend gemacht von mir -.-

**Comment by bedivere** [comment]
@reneeb danke für deinen Link und viel Spaß beim programmieren. Ich selber habe noch gar keine Erfahrungen bisher damit gemacht, dachte immer, das geht nur über iframe-Hacks oder so, zumindest dachte ich, das so mal irgendwo gelesen zu haben
